#!/bin/bash
# Agentic Sprint Kit — Bootstrap Script
#
# Usage:
#   ./bootstrap.sh [target-directory]          # New project: copy kit into target
#   ./bootstrap.sh --redo [source-directory]   # Redo: create redo_<name>/ and bootstrap it
#
# The `ccn` command (installed by setup.sh) wraps this with Claude auto-launch.
# Use bootstrap.sh directly if you want to set up the kit without launching Claude.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REDO_MODE=false

# Parse arguments
if [ "$1" = "--redo" ]; then
  REDO_MODE=true
  SOURCE_DIR="${2:-.}"
  SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd)"
  FOLDER_NAME="$(basename "$SOURCE_DIR")"
  TARGET_DIR="$(dirname "$SOURCE_DIR")/redo_${FOLDER_NAME}"
else
  TARGET_DIR="${1:-.}"
fi

# Resolve to absolute path (for non-redo mode)
if [ "$REDO_MODE" = false ]; then
  TARGET_DIR="$(cd "$TARGET_DIR" 2>/dev/null && pwd || mkdir -p "$TARGET_DIR" && cd "$TARGET_DIR" && pwd)"
fi

echo "=== Agentic Sprint Kit ==="
if [ "$REDO_MODE" = true ]; then
  echo "Mode: REDO"
  echo "Source project: $SOURCE_DIR"
  echo "New project:    $TARGET_DIR"
else
  echo "Mode: NEW PROJECT"
  echo "Setting up in:  $TARGET_DIR"
fi
echo ""

# Create target directory for redo mode
if [ "$REDO_MODE" = true ]; then
  if [ -d "$TARGET_DIR" ]; then
    echo "Error: $TARGET_DIR already exists. Remove it first or choose a different name."
    exit 1
  fi
  mkdir -p "$TARGET_DIR"
  TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"
fi

# Copy template files (don't overwrite existing files)
copy_if_missing() {
  local src="$1"
  local dest="$2"
  if [ ! -f "$dest" ]; then
    cp "$src" "$dest"
    echo "  Created: $(basename "$dest")"
  else
    echo "  Skipped: $(basename "$dest") (already exists)"
  fi
}

# Copy directory recursively (don't overwrite existing files)
copy_dir() {
  local src_dir="$1"
  local dest_dir="$2"
  mkdir -p "$dest_dir"
  for f in "$src_dir"/*; do
    [ -e "$f" ] || continue
    local base="$(basename "$f")"
    if [ -d "$f" ]; then
      copy_dir "$f" "$dest_dir/$base"
    else
      copy_if_missing "$f" "$dest_dir/$base"
    fi
  done
}

# Create directories
mkdir -p "$TARGET_DIR/docs"
mkdir -p "$TARGET_DIR/agent_docs"
mkdir -p "$TARGET_DIR/.claude/skills"

# Copy core files
# In redo mode, skip PROMPT.md — it will be generated by the redo intake
if [ "$REDO_MODE" = false ]; then
  copy_if_missing "$SCRIPT_DIR/PROMPT.md" "$TARGET_DIR/PROMPT.md"
fi
copy_if_missing "$SCRIPT_DIR/CLAUDE.md" "$TARGET_DIR/CLAUDE.md"
copy_if_missing "$SCRIPT_DIR/BEST_PRACTICES.md" "$TARGET_DIR/BEST_PRACTICES.md"

# Copy agent_docs
copy_dir "$SCRIPT_DIR/agent_docs" "$TARGET_DIR/agent_docs"

# Copy doc templates
for f in "$SCRIPT_DIR/docs/"*.md; do
  [ -f "$f" ] && copy_if_missing "$f" "$TARGET_DIR/docs/$(basename "$f")"
done

# Copy skills
copy_dir "$SCRIPT_DIR/.claude/skills" "$TARGET_DIR/.claude/skills"

# Copy settings.json
if [ -f "$SCRIPT_DIR/.claude/settings.json" ]; then
  copy_if_missing "$SCRIPT_DIR/.claude/settings.json" "$TARGET_DIR/.claude/settings.json"
fi

# Initialize git if needed
if [ ! -d "$TARGET_DIR/.git" ]; then
  cd "$TARGET_DIR" && git init -q
  echo "  Initialized git repository"
fi

# Create .gitignore if missing
if [ ! -f "$TARGET_DIR/.gitignore" ]; then
  cat > "$TARGET_DIR/.gitignore" << 'GITIGNORE'
node_modules/
.env
.env.local
dist/
build/
__pycache__/
*.pyc
.DS_Store
*.log
coverage/
.next/
.claude/settings.local.json
GITIGNORE
  echo "  Created: .gitignore"
fi

# Redo mode: write a marker file so the orchestrator knows this is a redo
if [ "$REDO_MODE" = true ]; then
  cat > "$TARGET_DIR/.redo" << EOF
ORIGINAL_PROJECT=$SOURCE_DIR
FOLDER_NAME=$FOLDER_NAME
CREATED=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
  echo "  Created: .redo (redo mode marker)"
fi

echo ""
echo "=== Setup Complete ==="
echo ""

if [ "$REDO_MODE" = true ]; then
  echo "Next steps:"
  echo "  1. cd $TARGET_DIR"
  echo "  2. Run: claude --redo"
  echo "     (or use 'ccn --redo' which does all of this automatically)"
  echo "  3. The agent will analyze $SOURCE_DIR and ask clarifying questions"
  echo "  4. Answer the questions and let it rebuild"
else
  echo "Next steps:"
  echo "  1. Edit PROMPT.md with your project description"
  echo "  2. Run: claude"
  echo "  3. Answer the clarifying questions (at most 10)"
  echo "  4. Let it build"
  echo ""
  echo "Or use 'ccn' to do all of this with a single one-liner."
fi
echo ""
